/* interface Mcode */
extern void Mcode_5finit(void);
#define Mcode__MHALT_3dBOX0 8
#define Mcode__MHALT (mk_box0(8))
#define Mcode__MLABEL_3dBOX1 7
#define Mcode__MLABEL(X1) (mk_box1(7,(X1)))
#define Mcode__MPUT_3dBOX1 6
#define Mcode__MPUT(X1) (mk_box1(6,(X1)))
#define Mcode__MGET_3dBOX1 5
#define Mcode__MGET(X1) (mk_box1(5,(X1)))
#define Mcode__MSTO_3dBOX1 4
#define Mcode__MSTO(X1) (mk_box1(4,(X1)))
#define Mcode__MLOAD_3dBOX1 3
#define Mcode__MLOAD(X1) (mk_box1(3,(X1)))
#define Mcode__MJMP_3dBOX1 2
#define Mcode__MJMP(X1) (mk_box1(2,(X1)))
#define Mcode__MJ_3dBOX2 1
#define Mcode__MJ(X1,X2) (mk_box2(1,(X1),(X2)))
#define Mcode__MB_3dBOX2 0
#define Mcode__MB(X1,X2) (mk_box2(0,(X1),(X2)))
#define Mcode__MDIV_3dINT 3
#define Mcode__MDIV (mk_icon(3))
#define Mcode__MMULT_3dINT 2
#define Mcode__MMULT (mk_icon(2))
#define Mcode__MSUB_3dINT 1
#define Mcode__MSUB (mk_icon(1))
#define Mcode__MADD_3dINT 0
#define Mcode__MADD (mk_icon(0))
#define Mcode__MJZ_3dINT 5
#define Mcode__MJZ (mk_icon(5))
#define Mcode__MJPZ_3dINT 4
#define Mcode__MJPZ (mk_icon(4))
#define Mcode__MJNZ_3dINT 3
#define Mcode__MJNZ (mk_icon(3))
#define Mcode__MJN_3dINT 2
#define Mcode__MJN (mk_icon(2))
#define Mcode__MJP_3dINT 1
#define Mcode__MJP (mk_icon(1))
#define Mcode__MJNP_3dINT 0
#define Mcode__MJNP (mk_icon(0))
#define Mcode__L_3dBOX1 3
#define Mcode__L(X1) (mk_box1(3,(X1)))
#define Mcode__T_3dBOX1 2
#define Mcode__T(X1) (mk_box1(2,(X1)))
#define Mcode__N_3dBOX1 1
#define Mcode__N(X1) (mk_box1(1,(X1)))
#define Mcode__I_3dBOX1 0
#define Mcode__I(X1) (mk_box1(0,(X1)))
