/* interface Dynamic */
extern void Dynamic_5finit(void);
extern struct rml_gval Dynamic__state0;
extern struct rml_gval Dynamic__env0;
extern RML_FORWARD_LABEL(Dynamic__evaluate);
#define Dynamic__CLOSURE_3dBOX3 0
#define Dynamic__CLOSURE(X1,X2,X3) (mk_box3(0,(X1),(X2),(X3)))
#define Dynamic__PRIM_3dBOX1 8
#define Dynamic__PRIM(X1) (mk_box1(8,(X1)))
#define Dynamic__CLO_3dBOX1 7
#define Dynamic__CLO(X1) (mk_box1(7,(X1)))
#define Dynamic__PAIR_3dBOX2 6
#define Dynamic__PAIR(X1,X2) (mk_box2(6,(X1),(X2)))
#define Dynamic__UNIT_3dBOX0 5
#define Dynamic__UNIT (mk_box0(5))
#define Dynamic__REF_3dBOX1 4
#define Dynamic__REF(X1) (mk_box1(4,(X1)))
#define Dynamic__BOOL_3dBOX1 3
#define Dynamic__BOOL(X1) (mk_box1(3,(X1)))
#define Dynamic__STRING_3dBOX1 2
#define Dynamic__STRING(X1) (mk_box1(2,(X1)))
#define Dynamic__REAL_3dBOX1 1
#define Dynamic__REAL(X1) (mk_box1(1,(X1)))
#define Dynamic__INT_3dBOX1 0
#define Dynamic__INT(X1) (mk_box1(0,(X1)))
#define Dynamic__P2_3dBOX1 1
#define Dynamic__P2(X1) (mk_box1(1,(X1)))
#define Dynamic__P1_3dBOX1 0
#define Dynamic__P1(X1) (mk_box1(0,(X1)))
#define Dynamic__P1PRINT_3dINT 6
#define Dynamic__P1PRINT (mk_icon(6))
#define Dynamic__P1CONS_3dINT 5
#define Dynamic__P1CONS (mk_icon(5))
#define Dynamic__P1TL_3dINT 4
#define Dynamic__P1TL (mk_icon(4))
#define Dynamic__P1HD_3dINT 3
#define Dynamic__P1HD (mk_icon(3))
#define Dynamic__P1NULL_3dINT 2
#define Dynamic__P1NULL (mk_icon(2))
#define Dynamic__P1GET_3dINT 1
#define Dynamic__P1GET (mk_icon(1))
#define Dynamic__P1REF_3dINT 0
#define Dynamic__P1REF (mk_icon(0))
#define Dynamic__P2RDIV_3dINT 11
#define Dynamic__P2RDIV (mk_icon(11))
#define Dynamic__P2IMOD_3dINT 10
#define Dynamic__P2IMOD (mk_icon(10))
#define Dynamic__P2IDIV_3dINT 9
#define Dynamic__P2IDIV (mk_icon(9))
#define Dynamic__P2MUL_3dINT 8
#define Dynamic__P2MUL (mk_icon(8))
#define Dynamic__P2SUB_3dINT 7
#define Dynamic__P2SUB (mk_icon(7))
#define Dynamic__P2ADD_3dINT 6
#define Dynamic__P2ADD (mk_icon(6))
#define Dynamic__P2LE_3dINT 5
#define Dynamic__P2LE (mk_icon(5))
#define Dynamic__P2LT_3dINT 4
#define Dynamic__P2LT (mk_icon(4))
#define Dynamic__P2EQ_3dINT 3
#define Dynamic__P2EQ (mk_icon(3))
#define Dynamic__P2SND_3dINT 2
#define Dynamic__P2SND (mk_icon(2))
#define Dynamic__P2FST_3dINT 1
#define Dynamic__P2FST (mk_icon(1))
#define Dynamic__P2SET_3dINT 0
#define Dynamic__P2SET (mk_icon(0))
